[theme]
# Primary accent color for interactive elements.
primaryColor = "#00802b"

# Background color for the main content area.
backgroundColor = ""

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Background color used for the sidebar and most interactive widgets.
spiderWeb = "#586e75"

# Color used for almost all text.
textColor = "#000000"